### ISSUE TITLE
ToDo Liste erstellen 

### ISSUE THREAD

**Issue by holber0** [holber0/portalfraese#1]
Tasks mit den ToDos erstellen.

**Comment by mike202002** [comment]
- [ ] Verbindung Kreuzplatte zu KUS konstruieren
- [ ] Verbindung Kreuzplatte zu KUS fertigen
- [x] Z-Motor Aufnahme an Kreuzplatte konstruieren
- [ ] Z-Motor Aufnahme fertigen
- [ ] Schrauben (Senkkopf und Innensechskant)
- [x] Z-Motor umbauen
- [x] Z-Motor einstellen
- [x] Sensorhalter konstruieren
- [ ] Sensorhalter drucken
- [ ] Sensoren verkabeln und anschließen
- [ ] Sensoren in Steuerung einbinden
- [x] Bearbeitungsfläche neu ausmessen und config bearbeiten
- [ ] Fräse ausrichten
- [ ] Opferplatte planen
- [ ] Planfräser kaufen
